services:
  obs-vnc:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: obs_vnc_container
    privileged: true
    volumes:
      - /shared:/shared  # Shared directory
    environment:
      - VNC_PASSWD=123456  # Default VNC password
    devices:
      - /dev/dri:/dev/dri  # GPU device
    group_add:
      - video
    restart: always
    shm_size: "256m"  # Shared memory for X11 and hardware encoding
